### PR TITLE
Fix NPE with BLS

### LINKED ISSUE #12968: Crash when selecting "done" in the texture pack selection Gui
### Your GTNH Discord Username

Alexdoru#9395

### Your Pack Version

2.3.1

### Your Server

solo

### Java Version

Java 8

### Type of Server

None

### Your Actions

open the ressource pack menu, select a texture pack to be loaded and click "done" to load it, it crashed

### Crash Report

[crash-2023-03-20_17.39.07-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11020902/crash-2023-03-20_17.39.07-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

### PR DESCRIPTION
**Pull request by glowredman**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12968

`ProgressDisplayer#displayer` is only nonnull during startup but resources can still be reloaded after that.

### CODE REVIEW

File: src/main/java/glowredman/txloader/progress/ProgressBarProxy.java [hunk 1]
```diff
@@ -1,11 +1,45 @@
...
+                // This shouldn't be reached...
+                // In case it is, cause early exits in the future
+                isBLSLoaded = false;
+                ProgressDisplayer = null;
+                return false;
+            }
+        }
+
+        try {
+            return displayer.get(null) != null;
```
Comment (minecraft7771) [inline src/main/java/glowredman/txloader/progress/ProgressBarProxy.java:33]: Does `displayer.get(null)` actually work? I think it will throw argument exception

Comment (glowredman) [reply src/main/java/glowredman/txloader/progress/ProgressBarProxy.java:33]: You can use `null` if the field is static

**Review by minecraft7771 — APPROVED** [review]
